### ISSUE TITLE
Some Additional ASNs from Bad Actors

### ISSUE THREAD

**Issue by vdzpro** [wallacebrf/dns#1]
Thank you for your hard work on these block lists, reduces a lot of failed logins on our VPN gateway. I found some additional ASNs not in your list that are commonly used by bad actors based on seeing incoming failed logins.

Latitude Hosting: AS396356
Clouvider Hosting: AS62240

Hope this helps. Keep up the good work!

**Comment by wallacebrf** [comment]
appreciate it and i am happy it is helping!
i will update the script and i will upload a new asn block list file shortly

**Comment by wallacebrf** [comment]
https://asn.ipinfo.app/api/text/list/AS62240 #Clouvider Hosting is already in the ASN blacklist

Latitude Hosting: AS396356 is not and i will be adding it

**Comment by wallacebrf** [comment]
i have confirmed that the IP lists for 
Latitude Hosting: AS396356
Clouvider Hosting: AS62240

are now included in the latest ASN block list file
https://github.com/wallacebrf/dns/blob/main/asn_block1.1.txt

**Comment by wallacebrf** [comment]
please feel free to continue sending me suggestions for additional server hosting companies as they are a real pain as people can spin up a server easily and start brute force attacking

**Comment by vdzpro** [comment]
> https://asn.ipinfo.app/api/text/list/AS62240 #Clouvider Hosting is already in the ASN blacklist
> 
> Latitude Hosting: AS396356 is not and i will be adding it

That is interesting. I did a search of the external connector entries and found the subnet 92.119.36.0/24 is not in the list even though it is part of Cloudvider's ASN. Maybe the ipinfo.app IP list is a bit out of date. I searched on the Cloudvider api entry you provided above and it isn't listed there.

I'm using https://hackertarget.com/as-ip-lookup/ to confirm ASL IP lists.

No problem if it's somewhat out of date, I have another list I'm maintaining to pick up the missed ones.

**Comment by wallacebrf** [comment]
> > https://asn.ipinfo.app/api/text/list/AS62240 #Clouvider Hosting is already in the ASN blacklist
> > Latitude Hosting: AS396356 is not and i will be adding it
> 
> That is interesting. I did a search of the external connector entries and found the subnet 92.119.36.0/24 is not in the list even though it is part of Cloudvider's ASN. Maybe the ipinfo.app IP list is a bit out of date. I searched on the Cloudvider api entry you provided above and it isn't listed there.
> 
> I'm using https://hackertarget.com/as-ip-lookup/ to confirm ASN IP lists. They have a free API with up to 50 queries a day.
> 
> No problem if ipinfo.app is missing a few, I have another list I'm maintaining to pick up the missed ones.

yea, i am sure these different providers are just not updated as quickly as everyone else. 

my script exceeds 50x queries per refresh so i do not use ones that throttle like that... that might be why ipinfo is a little out of date.

**Comment by vdzpro** [comment]
> > > https://asn.ipinfo.app/api/text/list/AS62240 #Clouvider Hosting is already in the ASN blacklist
> > > Latitude Hosting: AS396356 is not and i will be adding it
> > 
> > 
> > That is interesting. I did a search of the external connector entries and found the subnet 92.119.36.0/24 is not in the list even though it is part of Cloudvider's ASN. Maybe the ipinfo.app IP list is a bit out of date. I searched on the Cloudvider api entry you provided above and it isn't listed there.
> > I'm using https://hackertarget.com/as-ip-lookup/ to confirm ASN IP lists. They have a free API with up to 50 queries a day.
> > No problem if ipinfo.app is missing a few, I have another list I'm maintaining to pick up the missed ones.
> 
> yea, i am sure these different providers are just not updated as quickly as everyone else.
> 
> my script exceeds 50x queries per refresh so i do not use ones that throttle like that... that might be why ipinfo is a little out of date.

That makes sense. Thanks for adding in Latitude. I'll let you know if I see any more ASNs supporting bad actors. Have a good day.
