### ISSUE TITLE
Some More Datacenter ASNs

### ISSUE THREAD

**Issue by vdzpro** [wallacebrf/dns#2]
Here are a few more from the last few days. Sorry if you already have these.
AS62744 #Quintex Alliance Consulting
AS56971 #CGI Global Limited
AS210644 #Aeza International Ltd

**Comment by wallacebrf** [comment]
all three of those are new and not currently in the list. 

i am currently traveling for work and will update the github as soon as i can

**Comment by wallacebrf** [comment]
the three ASNs have been added and all files have been updated.

**Comment by vdzpro** [comment]
Thank you for updating this.

Jonathan van der Zee

From: wallacebrf ***@***.***>
Date: Thursday, December 26, 2024 at 7:26 AM
To: wallacebrf/dns ***@***.***>
Cc: Jonathan van der Zee ***@***.***>, Author ***@***.***>
Subject: Re: [wallacebrf/dns] Some More Datacenter ASNs (Issue #2)

the three ASNs have been added and all files have been updated.
